os: linux
sudo: false
dist: trusty

language: node_js
node_js: 10

before_install:
  - bash ./scripts/travis-install.sh

install: yarn install

script:
  - bash ./scripts/travis-script.sh

cache:
  yarn: true

notifications:
  email: false
