os: linux
sudo: required
dist: trusty

language: node_js
node_js: 
  - '10'

before_install: echo "//npm.pkg.github.com/:_authToken=$GPR_TOKEN" >> ~/.npmrc

install: npm ci

script:
  - npm run lint
  - npm run compile:test

cache:
  npm: true

notifications:
  email: false
