os: linux
sudo: required
dist: trusty

language: node_js
node_js: 
  - '12'

before_install: echo "//npm.pkg.github.com/:_authToken=$GPR_TOKEN" >> ~/.npmrc

install: npm ci

script:
  - npm run lint
  - npm run compile:test

cache: npm

notifications:
  email: false
